### ISSUE TITLE
Incompatible with nodejs 13.6

### ISSUE THREAD

**Issue by qwIvan** [zakplus/obfuscator-loader#11]
> Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
    at getTargets (/home/ivan/tapdata-admin/node_modules/inversify/lib/planning/reflection_utils.js:33:15)
    at Object.getDependencies (/home/ivan/tapdata-admin/node_modules/inversify/lib/planning/reflection_utils.js:11:19)
    at /home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:106:51
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:94:20)
    at /home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:108:17
    at Array.forEach (<anonymous>)
    at /home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:107:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/home/ivan/tapdata-admin/node_modules/inversify/lib/planning/planner.js:129:9)
    at /home/ivan/tapdata-admin/node_modules/inversify/lib/container/container.js:316:37
    at Container._get (/home/ivan/tapdata-admin/node_modules/inversify/lib/container/container.js:309:44)
    at Container.getTagged (/home/ivan/tapdata-admin/node_modules/inversify/lib/container/container.js:231:21)
    at Container.getNamed (/home/ivan/tapdata-admin/node_modules/inversify/lib/container/container.js:234:21)
    at e.nodeTransformerFactory (/home/ivan/tapdata-admin/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/InversifyContainerFacade.ts:75:61)

**Comment by dan-online** [comment]
I am also seeing this on node 13.5

**Comment by predte4a** [comment]
Can someone f***ing publish version 1.1.4?

**Comment by gurisko** [comment]
It is time to fork this.

EDIT: You can try [my fork](https://www.npmjs.com/package/awesome-obfuscator-loader)

**Comment by pbadenski** [comment]
@gurisko Thanks! I can't submit any issues for `awesome-obfuscator-loader`.. but could you do another round of upgrades to javascript-obfuscator@1.7.0?

**Comment by sanex3339** [comment]
Hi I bundled loader to the `webpack-obfuscator` plugin.
So, now it'll be updated together with `javascript-obfuscator` itself.

Please mark `awesome-obfuscator-loader` as deprecated it feel free to contribute to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage

**Comment by gurisko** [comment]
@sanex3339 No, thank you. I am not comfortable with the licensing of your project.

**Comment by gurisko** [comment]
@sanex3339 Done

**Comment by sanex3339** [comment]
Thank you!

**Comment by sanex3339** [comment]
Feel free to contribute, if you want.
