### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by Samerkassem** [zakplus/obfuscator-loader#14]
When I am doing npm run build, I am getting:

```
ERROR in ./index.js
Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
    at getTargets (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\reflection_utils.js:33:15)
    at Object.getDependencies (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\reflection_utils.js:11:19)   
    at F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:106:51
    at Array.forEach (<anonymous>)
    at _createSubRequests (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:94:20)
    at F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:108:17
    at Array.forEach (<anonymous>)
    at F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:107:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:94:20)
    at Object.plan (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\planning\planner.js:129:9)
    at F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\container\container.js:316:37
    at Container._get (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\container\container.js:309:44)
    at Container.getTagged (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\container\container.js:231:21)
    at Container.getNamed (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\inversify\lib\container\container.js:234:21)
    at e.nodeTransformerFactory (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\container\InversifyContainerFacade.ts:75:61)
    at e.value (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\TransformersRunner.ts:60:50)
    at e.value (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:236:49)
    at e.value (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:173:46)
    at e.value (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:138:72)
    at Function.value (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:27:85)
    at Object.obfuscator (F:\Downloads\AllFineonProjects\FineonFO\azure-fineon-webapp-fo\client\node_modules\obfuscator-loader\lib\index.js:47:50)
Child HtmlWebpackCompiler:
     4 assets
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 5.4 KiB {0} [built]
    [2] ./images/logoutIcon.png 65 bytes {0} [built]
    [3] ./images/FineonLogooriginal.png 73 bytes {0} [built]
    [4] ./images/white-logo-small.png 71 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fineon@1.0.0 build: `webpack --config ./webpack.prod.config.js --progress`npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fineon@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Samer\AppData\Roaming\npm-cache\_logs\2020-04-26T12_16_01_413Z-debug.log
```

my webpack config:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CompressionPlugin = require('compression-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  mode: 'production',
  entry: {
    app: './index.js',
  },
  module: {
    rules: [
      {
        test: /\.html$/i,
        use: [
          {
            loader: 'html-loader',
            options: {
              minimize: {
                removeComments: true,
                collapseWhitespace: true,
                collapseInlineTagWhitespace: true,
                minifyCSS: true,
                minifyJS: true,
              },
            },
          },
        ],
      },
      {
        test: /\.js$/i,
        exclude: /node_modules/,
        use: [
          {
            loader: 'obfuscator-loader',
            options: { compact: true },
          },
          {
            loader: 'babel-loader',
            query: { compact: false },
          },
        ],
      },
      {
        test: /\.(sass|scss|css)$/,
        exclude: /\.lazy\.(sass|scss|css)$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
      },
      {
        test: /\.lazy\.(sass|scss|css)$/i,
        use: [
          { loader: 'style-loader', options: { injectType: 'lazyStyleTag' } },
          'css-loader',
          'sass-loader',
        ],
      },
      {
        test: /\.(png|jpe?g|gif|ico|svg)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'assets/',
            },
          },
          'image-webpack-loader',
        ],
      },
      {
        test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'assets/',
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './index.html',
    }),
    new CleanWebpackPlugin(),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
     // html2pdf: 'html2pdf-fix-jspdf',
    }),
    new MiniCssExtractPlugin(),
    new OptimizeCssAssetsPlugin({
      cssProcessorPluginOptions: {
        preset: ['default', { discardComments: { removeAll: true } }],
      },
    }),
    new CompressionPlugin(),
  ],
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all',
        },
      },
    },
    minimize: true,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            comments: false,
          },
        },
        extractComments: false,
      }),
    ],
  },
};

```

I see nothing wrong, the build works fine if I remove the obfuscator-loader from config.

What am i doing wrong?

**Comment by ierover** [comment]
i have the same problem with u

**Comment by cwbeck** [comment]
same issue too.... (is there a fix!)

**Comment by henkjan33** [comment]
Same issue.. Would love a fix

Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.

**Comment by Rahulgarg30591** [comment]
I am unable to build my project right after installing the _obfuscator-loader_ using npm install --save-dev obfuscator-loader

**Comment by yhongm** [comment]
i have the same problem with u

**Comment by sanex3339** [comment]
Hi. Use loader bundled to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage
