### ISSUE TITLE
Cannot apply @injectable decorator multiple times.

### ISSUE THREAD

**Issue by Nantris** [zakplus/obfuscator-loader#5]
```
[1] [0] ./app/index.js 4.15 KiB {0} [built] [failed] [1 error]
[1]
[1] ERROR in ./app/index.js
[1] Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
[1] Error: Cannot apply @injectable decorator multiple times.
[1]     at C:\projects\myApp\node_modules\obfuscator-loader\node_modules\inversify\lib\annotation\injectable.js:8:19
[1]     at DecorateConstructor (C:\projects\myApp\node_modules\reflect-metadata\Reflect.ts:1202:35)
[1]     at Object.decorate (C:\projects\myApp\node_modules\reflect-metadata\Reflect.ts:742:24)
[1]     at _decorate (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\inversify\lib\annotation\decorator_utils.js:42:13)
[1]     at Object.decorate (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\inversify\lib\annotation\decorator_utils.js:55:9)
[1]     at Object.<anonymous> (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\event-emitters\ObfuscationEventEmitter.ts:7:9)
[1]     at r (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
[1]     at Object.<anonymous> (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\container\InversifyContainerFacade.ts:30:1)
[1]     at r (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
[1]     at Object.module.exports.Object.defineProperty.value (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:11:1)
[1]     at r (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
[1]     at Object.<anonymous> (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\index.ts:3:1)
[1]     at r (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
[1]     at C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:74:1
[1]     at Object.<anonymous> (C:\projects\myApp\node_modules\obfuscator-loader\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:74:1)
[1]     at Module._compile (C:\projects\myApp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[1]     at Module._compile (C:\projects\myApp\node_modules\pirates\lib\index.js:91:24)
[1]     at Module._extensions..js (module.js:663:10)
[1]     at Object.newLoader [as .js] (C:\projects\myApp\node_modules\pirates\lib\index.js:96:7)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1]     at Module.require (module.js:596:17)
[1]     at require (C:\projects\myApp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[1]     at Object.<anonymous> (C:\projects\myApp\node_modules\obfuscator-loader\lib\index.js:2:30)
[1]     at Module._compile (C:\projects\myApp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
[1]     at Module._compile (C:\projects\myApp\node_modules\pirates\lib\index.js:91:24)
[1]     at Module._extensions..js (module.js:663:10)
[1]     at Object.newLoader [as .js] (C:\projects\myApp\node_modules\pirates\lib\index.js:96:7)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1]     at Module.require (module.js:596:17)
[1]     at require (C:\projects\myApp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[1]     at loadLoader (C:\projects\myApp\node_modules\loader-runner\lib\loadLoader.js:13:17)
[1]     at iteratePitchingLoaders (C:\projects\myApp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
```

I'm probably just doing something wrong, but I'm not sure what.

Can you possibly expand on how to use this to obfuscate your own code, but exclude vendor modules? I'm not sure how to go about implementing this alongside my existing loaders, or if I can?

Thanks a lot! This project looks really interesting!

**Comment by youssef-lr** [comment]
Samer here. I had an issue with the obfuscator plugin as described here: https://github.com/javascript-obfuscator/webpack-obfuscator/issues/26, so I decided to use the loader instead and the same error as yours popped up.

**Comment by mezhevikin** [comment]
If you use obfuscator-loader, you should remove `const JavaScriptObfuscator = require('webpack-obfuscator');` from your webpack config.

**Comment by magurotuna** [comment]
Removing `const JavaScriptObfuscator = require('webpack-obfuscator')` works fine.  Thanks @mezhevikin
