### ISSUE TITLE
How to use obfuscator-loader with Vue-cli?

### ISSUE THREAD

**Issue by xiaolannuoyi** [zakplus/obfuscator-loader#7]
include: [ path.resolve(__dirname, "justMySources") ],
what is justMySources???
How to use obfuscator-loader for static files in vue-cli?
Can you give me an example?
Thank you.

**Comment by zakplus** [comment]
Hi xiaolannuoyi,
in that webpack configuration example, "justMySources" is the path to the directory containing your project source files. You need to specify that, otherwise the obfuscator would obfuscate also your dependency modules.  
Assuming your project structure is:
```
src/
  source_1.js
  source_2.js
webpack.config.js
```
then "justMySources" would be "src". Please note that the example makes use of path.resolve so "justMySources" is a path relative to __dirname (the webpack config file location).  

If you are using vue-cli 3, then you can create a [vue.config.js](https://cli.vuejs.org/guide/webpack.html#simple-configuration) file in the root of your project, next to package.json. The content of "configureWebpack" in the vue.config.js file will be merged into the webpack config file: 
```
// vue.config.js
const path = require('path');
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.js$/,
          include: [ path.resolve(__dirname, "<your src dir path here (relative to root)>") ],
          enforce: 'post',
          use: { loader: 'obfuscator-loader', options: {/* options here */} }
        },
      ]
    }
  }
}
```
Hope this helps!

**Comment by adrielwerlich** [comment]
Not working here... chrome console outputs lots of errors

#vue.config.js
```
const obfuscatorOptions = {
  compact: true,
  controlFlowFlattening: false,
  controlFlowFlatteningThreshold: 0.75,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 0.4,
  debugProtection: true,
  debugProtectionInterval: true,
  disableConsoleOutput: true,
  domainLock: [],
  identifierNamesGenerator: 'hexadecimal',
  identifiersPrefix: '',
  inputFileName: '',
  log: false,
  renameGlobals: true,
  reservedNames: [],
  reservedStrings: [],
  rotateStringArray: true,
  seed: 0,
  selfDefending: true,
  sourceMap: false,
  sourceMapBaseUrl: '',
  sourceMapFileName: '',
  sourceMapMode: 'separate',
  stringArray: true,
  stringArrayEncoding: true,
  stringArrayThreshold: 0.75,
  target: 'browser',
  transformObjectKeys: true,
  unicodeEscapeSequence: false
}

module.exports = {
  
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.js$/,
          include: [ path.resolve(__dirname, "./src") ],
          enforce: 'post',
          use: { loader: 'obfuscator-loader', options: obfuscatorOptions }
        },
      ]
    }
  }
}
```

```
Uncaught Error: Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
Error: Cannot apply @injectable decorator multiple times.
    at E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\inversify\lib\annotation\injectable.js:8:19
    at DecorateConstructor (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\reflect-metadata\Reflect.ts:1202:35)
    at Object.decorate (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\reflect-metadata\Reflect.ts:742:24)
    at _decorate (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\inversify\lib\annotation\decorator_utils.js:42:13)
    at Object.decorate (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\inversify\lib\annotation\decorator_utils.js:55:9)
    at Object.<anonymous> (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\event-emitters\ObfuscationEventEmitter.ts:7:9)
    at r (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
    at Object.<anonymous> (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\container\InversifyContainerFacade.ts:30:1)
    at r (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
    at Object.<anonymous> (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:11:1)
    at r (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
    at Object.<anonymous> (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\index.ts:3:1)
    at r (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:22:1)
    at E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:74:1
    at Object.<anonymous> (E:\downloads\whats-app-sender-dashboard\coreui-free-vue-admin-template-master\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\webpack\bootstrap:74:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at eval (webpack-internal:///./src/main.js:1:7)
    at Object../src/main.js (http://127.0.0.1:8080/app.js:1197:1)
    at __webpack_require__ (http://127.0.0.1:8080/app.js:724:30)
    at fn (http://127.0.0.1:8080/app.js:101:20)
    at Object.1 (http://127.0.0.1:8080/app.js:1211:18)
    at __webpack_require__ (http://127.0.0.1:8080/app.js:724:30)
    at http://127.0.0.1:8080/app.js:791:37
    at http://127.0.0.1:8080/app.js:794:10
```

![image](https://user-images.githubusercontent.com/20656722/61877067-a2d1eb00-aec4-11e9-814d-9a42b618fe84.png)

**Comment by sanex3339** [comment]
Hi. Use loader bundled to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage
