### ISSUE TITLE
Unexpected token ...(Spread Operators)

### ISSUE THREAD

**Issue by kiam123** [zakplus/obfuscator-loader#8]
```
[1]     ERROR in ./src/content/recorder-handlers.js
[1]     Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
[1]     Error: Line 400: Unexpected token ...
[1]         at ErrorHandler.constructError (/home/kr/kr/node_modules/esprima/dist/esprima.js:5012:22)
[1]         at ErrorHandler.createError (/home/kr/kr/node_modules/esprima/dist/esprima.js:5028:27)
[1]         at Parser.unexpectedTokenError (/home/kr/kr/node_modules/esprima/dist/esprima.js:1985:39)
[1]         at Parser.throwUnexpectedToken (/home/kr/kr/node_modules/esprima/dist/esprima.js:1995:21)
[1]         at Parser.parseObjectPropertyKey (/home/kr/kr/node_modules/esprima/dist/esprima.js:2499:33)
[1]         at Parser.parseObjectProperty (/home/kr/kr/node_modules/esprima/dist/esprima.js:2534:25)
[1]         at Parser.parseObjectInitializer (/home/kr/kr/node_modules/esprima/dist/esprima.js:2602:35)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parsePrimaryExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:2354:38)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parseLeftHandSideExpressionAllowCall (/home/kr/kr/node_modules/esprima/dist/esprima.js:2899:26)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parseUpdateExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3004:26)
[1]         at Parser.parseUnaryExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3048:26)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parseExponentiationExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3054:26)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parseBinaryExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3089:26)
[1]         at Parser.inheritCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2285:37)
[1]         at Parser.parseConditionalExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3141:26)
[1]         at Parser.parseAssignmentExpression (/home/kr/kr/node_modules/esprima/dist/esprima.js:3250:26)
[1]         at Parser.isolateCoverGrammar (/home/kr/kr/node_modules/esprima/dist/esprima.js:2269:37)
[1]         at Parser.parseLexicalBinding (/home/kr/kr/node_modules/esprima/dist/esprima.js:3434:26)
[1]         at Parser.parseBindingList (/home/kr/kr/node_modules/esprima/dist/esprima.js:3439:27)
[1]         at Parser.parseLexicalDeclaration (/home/kr/kr/node_modules/esprima/dist/esprima.js:3461:34)
[1]         at Parser.parseStatementListItem (/home/kr/kr/node_modules/esprima/dist/esprima.js:3385:69)
[1]         at Parser.parseBlock (/home/kr/kr/node_modules/esprima/dist/esprima.js:3405:30)
[1]         at Parser.parseStatement (/home/kr/kr/node_modules/esprima/dist/esprima.js:4109:39)
[1]         at Parser.parseIfClause (/home/kr/kr/node_modules/esprima/dist/esprima.js:3657:22)
[1]         at Parser.parseIfStatement (/home/kr/kr/node_modules/esprima/dist/esprima.js:3672:32)
[1]         at Parser.parseStatement (/home/kr/kr/node_modules/esprima/dist/esprima.js:4145:43)
[1]         at Parser.parseStatementListItem (/home/kr/kr/node_modules/esprima/dist/esprima.js:3388:39)
[1]         at Parser.parseBlock (/home/kr/kr/node_modules/esprima/dist/esprima.js:3405:30)
[1]         at Parser.parseStatement (/home/kr/kr/node_modules/esprima/dist/esprima.js:4109:39)
[1]         at Parser.parseIfClause (/home/kr/kr/node_modules/esprima/dist/esprima.js:3657:22)
[1]         at Parser.parseIfStatement (/home/kr/kr/node_modules/esprima/dist/esprima.js:3672:32)
[1]      @ ./src/content/recorder.js 168:0-59 630:0-20
[1]      @ ./src/content/content-initialization.js
[1]      @ multi ./src/content/command-receiver.js ./src/content/prompt-injecter.js ./src/content/content-initialization.js
```
In the description of obfuscator it said es6 is supported, but a build error happened at "..."(Spread Operators), What should I do to pass this?

**Comment by kiam123** [comment]
My webpack config
```
var path = require('path');
var HtmlWebPackPlugin = require('html-webpack-plugin');
var merge = require('webpack-merge');
var common = require('./webpack.common.js');
var common1 = require('./webpack.common.1.js');
const TerserPlugin = require('terser-webpack-plugin');
var cache = {};
module.exports = [
    merge(common1, {
        mode: 'production',
        entry: {
            "option/js/option": ["./src/option/js/options.js"],
            "background/background_script": ["./src/background/storage-initialization.js", "./src/background/background.js"],
            "content/document_start": ["./src/content/pageScript-injecter.js"],
            "content/document_end": ["./src/content/command-receiver.js", "./src/content/prompt-injecter.js", "./src/content/content-initialization.js"],
            "page/pageScript": ["./src/page/keys.js", "./src/page/autoWait.js", "./src/page/getListener.js", "./src/page/runScript.js", "./src/page/onsubmit.js"]
        },
        output: {
            filename: '[name].js',
            path: path.resolve(__dirname, './src'),
            libraryTarget: 'umd'
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    enforce: 'post',
                    use: {
                        loader: 'obfuscator-loader',
                        options: {
                            //exclude: ["node_modules"],
                            compact: false,
                            // deadCodeInjection: false,
                            //deadCodeInjectionThreshold: 1,
                            identifierNamesGenerator: 'hexadecimal',
                            unicodeEscapeSequence: true
                        }
                    }
                },
            ]
        },
    }),
    merge(common, {
        mode: 'development',
        entry: {
            react: ['./src/panel/js/UI/index.js'],
            initial: [
                'babel-polyfill',
                './src/panel/js/background/initial.js'
            ]
        },
        output: {
            path: path.resolve(__dirname, 'src/panel/js/UI/build'),
            library: 'Panel',
            libraryTarget: 'umd',
            filename: '[name].bundle.js'
        },
        devServer: {
            contentBase: path.join(__dirname, 'src/panel/js/UI/build')
        },
        module: {
            rules: [
                {
                    test: /\.(js|jsx)$/,
                    exclude: /node_modules/,
                    use: {
                        loader: "babel-loader",
                        options: {
                            presets: [['env', {
                                "targets": {
                                    "browsers": ["last 2 Chrome versions"]
                                },
                                "modules": "commonjs"
                            }]]
                        }
                    }
                }
            ]
        },
        plugins: [
            new HtmlWebPackPlugin({
                template: "./src/panel/index_react.html",
                filename: "index_react.html"
            })
        ]
    }),
    merge(common, {
        mode: 'development',
        entry: {
            entryPoint: ['./src/panel/js/UI/entryPoint.js']
        },
        output: {
            path: path.resolve(__dirname, 'src/panel/js/UI/build'),
            library: 'EntryPoint',
            libraryTarget: 'umd',
            filename: '[name].bundle.js'
        },
        devServer: {
            contentBase: path.join(__dirname, 'src/panel/js/UI/build')
        }
    })
];
```

**Comment by sanex3339** [comment]
Hi. Use loader bundled to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage
